### ISSUE TITLE
Prevent Markdown Preview from Jumping to Top after Every Change to Document

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1221]
One thing I've noticed in MM that can be a bit disruptive to the user's workflow is the markdown preview's tendency to jump to the beginning of the document after every change. This forces the user to click on the line of the document where they are working to force the preview to jump back to the current location in the document each time the document is edited (even a single character). It makes no difference if preview is displayed in a pane of the same window or in a separate window.  Is there a way to prevent this in-app?

**Comment by RickStrahl** [comment]
This has come up a few times:

https://github.com/RickStrahl/MarkdownMonster/issues/1215

I can't duplicate this behavior and it seems that even for a few people that have run into it it's isolated to specific machines.

The workaround is to turn off two-way preview sync (set to **Editor->Preview** in the status bar right hand corner) which prevents the recursive movement that is the likely culprit.

Any information you can provide is helpful specific to your setup as I do think this is environment related where somehow the refresh is delayed (keyboard utilities, custom keyboard themes perhaps) etc.

**Comment by pa-0** [comment]
Windows 11 Pro.  I'm away from my PC currently, but when I return to it I will get you the build info and other specs

**Comment by nonplayer** [comment]
Just adding some additional context here from my own experiences. My observation of this is only in very large documents, with two way sync enabled. I can only repeat this on one machine currently (Win11, Ryzen 9 6900S, 40g ram), and I suspect that's because all the other machines I have access to vastly outclass it in cpu and ram resources (my next lowest has 64g ram and does not have the issue). For reference, the document I'm experiencing it in is currently at 2971 lines of game design text.

It seems sometimes it can take a sec for the preview to sync, but then when the preview syncs it seems to want to also re-sync the editor immediately afterward, at least that's how it appears on my screen. Like it's detecting the re-sync on the right as an intended change, and then that tells the left to re-sync as well. I got tired of testing different things with it and just turned off two way sync as it was giving me a headache.

**Comment by pa-0** [comment]
I'm having this issue on a pretty high-end rig I built myself. Specs:

- Markdown Monster v3.9.5
- Windows 11 Pro 64-bit, OS Build: 26200.5751
- Liquid-cooled, Intel i9-14900K processor, 96GB DDR5 RAM, nvidia 4090 GPU, Asus Maximus z790 hero motherboard, so I don't know if it's just coiincidental that this only presents as an issue on your lower tier machine

**Comment by pa-0** [comment]
![Image](https://github.com/user-attachments/assets/90f2cd61-c405-40b5-88e9-674291fef066)

**Comment by nonplayer** [comment]
Ah I see now, and I misread your original post. My issue is similar, but the jumping I was getting is only on the editor itself. I don't get the "jump to the beginning" in the preview thing on my end. Instead, I was getting an apparent delay in the sync from editor to preview, which would then have a delay rebound sync from the preview back to the editor, causing it to repeatedly jump around.

**Comment by pa-0** [comment]
Also @RickStrahl I get this same behavior when I change the settings to one-way sync (Editor -> Preview)

**Comment by RickStrahl** [comment]
@nonplayer - yes, but it's most likely due to the preview moving and then triggering the editor to move. If the preview refresh is too slow (very large docs or docs with large tables or things like video/gif that take a long time to layout in Html) the scroll occurs after the timeout I allow to ignore the scroll. Then the preview scrolls and the editor adjusts. 

If that's the case though using Editor->Preview sync should most definitely not show this behavior.

@pa-0 If you're seeing this with Editor->Preview only then I don't know what would trigger that behavior. The editor won't scroll on its own unless you initiate it. The only thing that triggers editor scroll dynamically without user interaction is two-way or preview to editor sync. If you're seeing that I'd suspect something else is happening in your environment that's triggering the editor to move. Your screen shot doesn't show the statusbar that shows the preview sync status so i can't tell. From what I see it looks like the preview refreshes slow, then the editor moves which definitely suggests two-way sync is on.

**Comment by RickStrahl** [comment]
@pa-0 @nonplayer  A few more things to consider that can cause preview issues:

* **Using a non-default Markdown Parser**  
specifically Pandoc will not work reliably since it doesn't provide meta data for line numbers, so text has to be matched based on what's on the current line. I suspect that's what the problem is in the screen shot you posted since you type a single letter which likely exists at the top of the document. If you want the preview to work reliably use the default Markdig parser and switch to Pandoc  only to verify. There should be very little reason to use another Markdown parser (even if that is your target).   
If using PanDoc for preview you most definitely don't want two-way sync enabled.


* **JavaScript in the Page**
If your page contains embedded JavaScript it's likely that the JS code can drastically delay loading and may also force a full page reload. 


Post your entire screen including the status bar which shows more of the relevant state. Also perhaps you can share your markdown and dependencies to see if I can duplicate the behavior (if it's not the above).

**Comment by RickStrahl** [comment]
I just fixed a related issue that had to do with first line selection and noticed a potential problem with top selection.

In some cases when no line numbers can be mapped, MM tries to match the content based on a header Id or actual content in the document - in some cases however the line number (0) might be taking precendence which might have accounted for the navigation.

I've now removed the early exit so that the code continues on a 0 line number (and no headerId) and then still tries to find the content. That may very well be the problem and why it's specific to your document where content doesn't have a line number associated with it (ie. certain list items, tables, large code blocks, images etc.) and should be searching for content - but never actually gets to that part. 

The fix now always tries to find the content if passed and also doesn't navigate to top on no match. This also fixes first and second line line highlighting which previously wasn't working but unnoticed due to headers and FrontMatter.

Give this another shot in `v3.9.7.5` or later.

**Comment by pa-0** [comment]
Hi Rick, sorry for the late reply.  This is still presenting as an issue, when using Markdig as the parser rather than pandoc.

<img width="3840" height="2099" alt="Image" src="https://github.com/user-attachments/assets/59b1d48a-9b6a-4ed9-a6f9-a2104413717b" />

**Comment by RickStrahl** [comment]
Since I can't duplicate there's not much I can do about this.

* Does this happen just with a specific document or any document?
* Can you send me the doc (just in case there's some odd issue)

There's nothing that I can think of that would trigger the editor to 'jump' short of a full refresh of the editor which I can't think of a reason to happen other than explicitly refreshing (F5 or context). 

The only occasion where I've heard from other users is related to the two-way sync which is a known issue and something that can't really be avoided with certain types of documents but that's not in use here.

I'm out of ideas.

**Comment by pa-0** [comment]
> * Does this happen just with a specific document or any document?

This happens consistently with any doc. 
 
> * Can you send me the doc (just in case there's some odd issue)

As an example for reproduction of the issue (at least on my end), I downloaded the README from this repository using this link: https://github.com/RickStrahl/MarkdownMonster/raw/refs/heads/main/README.md

That said, it sounds like there really isn't much that can be done, so no worries. Thank you for having taken the time to try and fix it! I appreciate that.
