### ISSUE TITLE
Ctrl-N does not create new file

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#8]
If I just launch the app and press Ctrl-N, nothing seems to happen (no new file).  If I create one using the File -> New option a new file is opened.  At that point Ctrl-N seems to work as expected.

See image.  (I treid to upload a video, but GitHub doesn't like that.)

![markdown-monster-ctrl-n-not-working](https://cloud.githubusercontent.com/assets/1824392/15951300/f5769ebe-2e6b-11e6-854a-48187e999ec1.gif)

**Comment by RickStrahl** [comment]
Thank you. It's a known bug. It doesn't work when no document is open. It works when you're in a document.

I have to figure out how selectively decide which handler handles the Ctrl-n.

**Comment by RickStrahl** [comment]
Ok. figured out how to let the Editor ignore the Ctrl-N browser command and forward the key combo to WPF where it can be handled for either editor keys or on the window.

Fixed in 0.29.1 (you'll have to manually update)

**Comment by daughtkom** [comment]
This is still an issue if the preview pane is in focus.  Then it opens the preview document in IE.
