### ISSUE TITLE
Suggestion: Drag&Drop for Document Outline

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#936]
Would be nice when we could drag items from the document outline (sidebar) into the document as an Anchor-link `[my Item](#my-item)` - the same way as we can drag files from the filelist.

**Comment by jbridgy** [comment]
I would like the suggested feature although the `Insert link` dialog (Ctrl+K) offers the same functionality indirectly via the `#` button.

What I miss more is the ability to **restructure the document**, that is, to rearrange the headings (including their bodies) by drag&drop within the Document Outline as it is possible within the Navigation pane of Word and LibreOffice Writer.

**Comment by realB12** [comment]
The Insert link dialog (Ctrl+K)  is many clicks and not very efficient compared with drat&drop. 

Restructuring the document in the sidebar would be nice, indeed - but I consider this as a separate feature request to mine. What do you think?

**Comment by jbridgy** [comment]
Done. See #949.

**Comment by realB12** [comment]
For me "Done" has another meaning. 
This is now the second time for me, that unsolved problem, required features and suggested solutions are not solved, not implemented etc. but has been decided to be good enough and that we have to stick with what we have (I still have major issues on Drag-Drop all over the place - but everything related to is is now "done") - and I am asking myself why I am taking my time to report and suggest issues, when they are just ticked off? 
I do not think it is fair, that everything that is nor really "done" is closed,  so that Issues look as if they are fixed. They are not!
I do not expect that issues are fixed (immediately) - not at all - but I expect that issues remain open, till they are fixed or we have another "hold" status where stuff goes on hold. 
"Done" for me is then when the customer is happy :-)

**Comment by jbridgy** [comment]
I am sorry for my misleading reply. "Done" just meant, that I created a separate feature request as you asked me to do.

> ... when closing this suggestion I think we are closing an opportunity for improvement.

Then why do have closed the suggestion yourself?
It seems to me that @RickStrahl (author of mm) has confused your request with mine. According to his response it is currently too hard to implement my request because it depends on [Markdig](https://github.com/xoofx/markdig), but your request is (much) simpler. So let's wait for a response from the author.

**Comment by RickStrahl** [comment]
Document Outline Drag and Drop into document has been implemented.

Produces:

```markdown
[#LinkId](Header Text)
```

in the document at dropped cursor location.
